### ISSUE TITLE
Suggestion, Other showcases?

### ISSUE THREAD

**Issue by TDarkShadow** [sapic/sapic#1]
How about one artwork showcase and possibility to change one of the other artwork showcase into a different showcase?

This would make a profile more unique or in line with a theme, to also show achievements for Level 20-.

**Comment by TrueCarry** [comment]
If you have another showcase in your steam profile, you can move it to top on sapic
![image](https://cloud.githubusercontent.com/assets/5431520/12362670/a69e3922-bbd5-11e5-926f-1292663fe334.png) by clicking arrows(result: 
![image](https://cloud.githubusercontent.com/assets/5431520/12362693/c9b61ec0-bbd5-11e5-8043-f4a7398f9234.png))
. If it's not what you meant, then describe your idea better please.
