### ISSUE TITLE
我有个提议

### ISSUE THREAD

**Issue by LeePich** [sapic/sapic#20]
或许可以增加这种模式
![chrome_2017-11-08_04-48-03 -](https://user-images.githubusercontent.com/14200959/32517797-77bf4282-c442-11e7-8ec5-bba2c89cbf28.jpg)

**Comment by TrueCarry** [comment]
Have you tried long artwork mode?

**Comment by LeePich** [comment]
我用过506 x 928 + 100 x 928

506 x 506 + 100 x 436我也尝试过这样的比例，上面截图就是这样，
我只是提议添加一种这样的模式
