### ISSUE TITLE
I can't download background

### ISSUE THREAD

**Issue by Qaig36** [sapic/sapic#37]
Hello
I can't download the background due to a missing button.
Browser google chrome 78.0.3904.97 version Windows 10
![problem](https://user-images.githubusercontent.com/57375799/68511927-4d54fa80-0277-11ea-872e-dd0db31465ce.png)

**Comment by TheOddball** [comment]
> Hello
> I can't download the background due to a missing button.
> Browser google chrome 78.0.3904.97 version Windows 10
> ![problem](https://user-images.githubusercontent.com/57375799/68511927-4d54fa80-0277-11ea-872e-dd0db31465ce.png)

?? Please elaborate

**Comment by Qaig36** [comment]
There is no "Download zip" option.
![guide1](https://user-images.githubusercontent.com/57375799/68532139-36b3af80-031a-11ea-8d5a-4d2800da3796.jpg)

**Comment by TheOddball** [comment]
PEBCAK.
Try looking a little closer, or get some glasses.
