### ISSUE TITLE
Customize cropping issues.

### ISSUE THREAD

**Issue by WalkingBest** [sapic/sapic#38]
Selecting "Shorten Right Image" on artwork showcase works visually but the downloaded image is full size.
![image](https://user-images.githubusercontent.com/17721093/69777931-40eb0000-119a-11ea-8d6d-e67de4642579.png)

And this is the result.
![image](https://user-images.githubusercontent.com/17721093/69777983-7e4f8d80-119a-11ea-8d2e-7358ceb60c07.png)

**Comment by TheOddball** [comment]
Oops... Fixed.
