### ISSUE TITLE
Animated Profile Backgrounds

### ISSUE THREAD

**Issue by SapuSeven** [sapic/sapic#40]
Hi,
is there any support for the new animated backgrounds planned?
Is it even possible?

**Comment by jQplay** [comment]
it's still the same template

**Comment by SapuSeven** [comment]
I mean will I be able to generate animated artwork that's matching the animated background?

**Comment by TheOddball** [comment]
@TrueCarry will have to add support in https://github.com/sapic/sapic-go

**Comment by TrueCarry** [comment]
Works on beta
