### ISSUE TITLE
"Car" Animated Background Delay / Out of sync after several minutes

### ISSUE THREAD

**Issue by realWhiteFoxy** [sapic/sapic#41]
_Originally reported by Post#0001 on Discord._

After several minutes the "Car" animated background doesn't sync properly (main/middle & right side artwork images).
![2321876](https://user-images.githubusercontent.com/59917543/86583129-20b5c780-bf59-11ea-821e-08e8abbe47dc.png)
![delay](https://user-images.githubusercontent.com/59917543/86583158-2f9c7a00-bf59-11ea-8d2a-6e6479d19898.gif)

**Comment by TrueCarry** [comment]
Webm and gif framerate couldn't be synchronized 100%.
