### ISSUE TITLE
"E.D.N. III Vista" Profile Background Misalignment 

### ISSUE THREAD

**Issue by realWhiteFoxy** [sapic/sapic#44]
"E.D.N. III Vista" appears to be misaligned:
https://steam.design/#https://steamcdn-a.akamaihd.net/steamcommunity/public/images/items/226720/4a7f3784347cf0a24611a34cbfc7e4af748974da.jpg

Originally reported by FreeZ#1697 on Discord.
I attached the correct/fixed crops for measuring purposes.

The issue affects both https://next.steam.design/ and https://steam.design/
![Artwork_Middle](https://user-images.githubusercontent.com/59917543/91373728-7dad5b80-e7ed-11ea-9a76-e4069041f178.png)
![Artwork_Right_Top](https://user-images.githubusercontent.com/59917543/91373764-9158c200-e7ed-11ea-8de1-9d1bc5471875.png)

**Comment by TheOddball** [comment]
Please re test this on latest site version

**Comment by realWhiteFoxy** [comment]
Still not fixed after the update.

**Comment by TrueCarry** [comment]
Solved by https://github.com/sapic/sapic/pull/55
