### ISSUE TITLE
Possibly add a LICENSE to the repo

### ISSUE THREAD

**Issue by makinori** [sapic/sapic#51]
Just a while ago there were some issues with https://steam.design and I offered a temporary fix hosted on another url.

Soon after posting on the Discord I was banned without given reason. I can only guess this project is not to be redistributed and I'm sorry for violating this. I was only trying to help others, so I suggest adding a license! This will help other people know if this happens again in the future. I immediately shut down my distribution.

Even just a "don't distribute" in the README would help. Thank you for all your hard work.

**Comment by TheOddball** [comment]
You have been unbanned, I apologise. One of our staff members had banned you for believing that you were scamming people with a fake URL. Again, I apologise.
