### ISSUE TITLE
[Animated Backgrounds] Getting crops from different backgrounds

### ISSUE THREAD

**Issue by realWhiteFoxy** [sapic/sapic#53]
When trying to crop the following animated background...
https://steamcdn-a.akamaihd.net/steamcommunity/public/images/items/870780/acb9b58a87f1b1e0d0e866f383ccf3543530426f.webm

The site gives crops for...
https://steamcdn-a.akamaihd.net/steamcommunity/public/images/items/1263950/4d466f77edf3265a253fba79d47bc91a37e34920.webm

Originally reported by Dryden.exe#0020  on Discord

**Comment by ReLyf** [comment]
it also seems like every time you download an animated background it redirect you into downloading the black hole one

so its not a specific background problem

**Comment by realWhiteFoxy** [comment]
Fixed.
