### ISSUE TITLE
Add ability to crop background image for the "Featured Artwork Showcase" that doesn't have any side images.

### ISSUE THREAD

**Issue by Blakeinstein** [sapic/sapic#54]
A new addition to the points shop was a featured artwork showcase, that only displays a single image. Quite handy if you want to you use your artwork showcase as its intended.

**Comment by realWhiteFoxy** [comment]
Already implemented - Open the ZIP file and look for "Artwork_Featured"

**Comment by Blakeinstein** [comment]
Ah well... okay then.
