### ISSUE TITLE
Stops at ffmpeg-core initialization (on Firefox)

### ISSUE THREAD

**Issue by maroru** [sapic/sapic#57]
Using both Firefox and Firefox private (incognito) mode the converter stops at ffmpeg-core initialization.

```
logs:

 use ffmpeg.wasm v0.9.5
load ffmpeg-core
loading ffmpeg-core
fetch ffmpeg-core.worker.js script
worker object URL=blob:https://steam.design/9d86ec8c-f261-44f8-9207-e08c1dc2f01f
download ffmpeg-core script (~25 MB) from https://unpkg.com/@ffmpeg/core@0.8.4/dist/ffmpeg-core.js
initialize ffmpeg-core
```
This is the error shown in the console
![image](https://user-images.githubusercontent.com/31323152/107159131-d3b52c00-6953-11eb-990a-a9800d580eb5.png)
I switched to chrome and ffmpeg-core was successfully initialized and loaded.

**Comment by TrueCarry** [comment]
It's the problem with FF, can't fix for now.
