### ISSUE TITLE
Add option to choose color scheme for profile

### ISSUE THREAD

**Issue by ghost** [sapic/sapic#83]
Steam has ability to set custom color schemes:
`DefaultTheme`, `SummerTheme`, `MidnightTheme`, `SteelTheme`, `CosmicTheme`, `DarkModeTheme` are already available for all users for free.

**However, there are a lot of other colors schemes from 'Game Profiles' Point Shop section which you can't preview with your background.**

When you set color scheme it changes class in body. In my opinion we can parse all available color schemes and make an option to choose color scheme
![image](https://user-images.githubusercontent.com/8164054/182016307-4958b49a-e661-4f05-b2ff-78c4fa398c59.png)

**Comment by ghost** [comment]
Extra color schemes classes I found in 'Game Profiles' section:
`VibrantBlueTheme` `SteamGreenTheme` `MutedBlueTheme` `GoldTheme`  `GoldBurgundyTheme` `PurpleTheme` `GreenSlimeTheme` `FlatGreyTheme` `BurntOrangeTheme` `Winter2021Theme` `MurugiahTheme` `ColorNightmareTheme` `GhostTheme` `Lunar2022Theme` `MutedRedTheme` `PinkTealTheme` `BlueRedTheme`

**Comment by TheOddball** [comment]
Unfortunately, with the way the site is designed, this isn't possible without massive rewrites.
It is a good idea, but it's not a development priority.
Additionally, it's not a tool that helps with the core idea of the site, I see the effort required very much not worth the payoff.
